"""make subscription one to one with order item

Revision ID: 2450a3b5e25b
Revises: 4e7b61363cc1
Create Date: 2026-09-01 15:22:23.260486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2450a3b5e25b'
down_revision: Union[str, Sequence[str], None] = '4e7b61363cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'subscriptions', ['item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    # ### end Alembic commands ###
