"""add volume feature to service plans

Revision ID: 889068ab98c8
Revises: 2450a3b5e25b
Create Date: 2026-09-01 16:25:54.088024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889068ab98c8'
down_revision: Union[str, Sequence[str], None] = '2450a3b5e25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('traffic', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'traffic')
    # ### end Alembic commands ###
